/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/


function fiboEvenSum(num) {  
    let first = 1;
    let second = 2;
    let temp ;
    let evenCount = 0;
    while(first <= num){
      temp = second;
      second += first;
      first = temp;
      if (first % 2 == 0){
        evenCount+=first
      }
  
    }
    return evenCount
  
  }
  
console.log(fiboEvenSum(60));

  